---
#
# tasks file for ansible-role-readahead_setup
#
# vim:et:ts=2:ft=ansible

- name: Enumerate disks
  command: lsblk --raw --noheadings --nodeps --output NAME
  register: block_devices
  always_run: True

- name: Modify rc.local to increase read_ahead buffer for disks
  lineinfile: dest=/etc/rc.local line='/bin/echo 4096 > /sys/block/{{ item }}/queue/read_ahead_kb' insertbefore='exit 0'
  with_items: block_devices.stdout_lines

- name: Activate increased read_ahead buffer for disks now
  shell: /bin/echo 4096 > /sys/block/{{ item }}/queue/read_ahead_kb
  with_items: block_devices.stdout_lines

